songs_app/urls.py
from django.urls import path
from . import views

app_name = 'songs_app'
# Sets app name to song's app so template tagging can be used

urlpatterns = [
    path('', views.index, name='index'),
    path('lyrics/', views.lyrics, name='lyrics'),
    path('random_song/', views.random_song, name='random_song'),
    path('top_songs/', views.top_songs, name='top_songs'),
]

songs_project/urls.py
from django.contrib import admin
from django.urls import path, include
from songs_app import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    path('songs_app/', include('songs_app.urls', namespace='songs_app')),
]

songs_app/models.py
from django.db import models

class Artist(models.Model):
    # Class creates Artist model in the database
    artist = models.CharField(max_length=264, null=True)

    def __str__(self):
        return self.artist


class Song(models.Model):
    # Class creates Song model in database and is linked to Artist model
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    # artist is linked to Artist model, through a ForeignKey (One to many field)
    song = models.CharField(max_length=264)
    lyrics = models.TextField(null=True, blank=True)
    searches = models.IntegerField(default=1)

    class Meta:
        # Meta class ensures repeat entries are not stored in database
        unique_together = ['artist', 'song']
        # Unique together ensures that either artist or song must be unique to save to database

    def __str__(self):
        return self.song

songs_app/forms.py
from django import forms
from songs_app.models import Artist, Song

class ArtistChoice(forms.ModelForm):
# Class creates form for artist choice and links to Artist model

    class Meta():
        model = Artist
        fields = '__all__'
        # Links to all Artist fields (Only one in this case)

        labels = {'artist': ''}
        widgets = {
        'artist': forms.TextInput(attrs={'placeholder': 'Enter artist here'}),
    }
        # Removes label and adds placeholder to form


class SongChoice(forms.ModelForm):
    # Class creates form for song choice and links to Song model

    class Meta():
        model = Song
        fields = ('song',)
        # Links only to song field in Song model as artist fiels is linked to Artist model through a foreign key
        labels = {'song': ''}
        widgets = {
        'song': forms.TextInput(attrs={'placeholder': 'Enter song here'}),
    }
        # Removes label and adds placeholder to form

songs_app/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView
from songs_app.forms import SongChoice, ArtistChoice
from django.http import HttpResponseRedirect, HttpResponse
from songs_app.lyrics_generator import Lyrics
from songs_app.models import Artist, Song
from songs_app.query import random_song_generator, database_check, top_songs_generator
from django.db.models import F

def index(request):
    # View renders the website's index page
    artist_form = ArtistChoice()
    song_form = SongChoice()
    # Initiates instance of form classes

    if request.method == 'POST':
        artist_form = ArtistChoice(data=request.POST)
        song_form = SongChoice(data=request.POST)
        # Checks if forms send post requests and saves form inputs to corresponding variables

        if artist_form.is_valid() and song_form.is_valid():
            # Checks forms are valid and cleans data if they are.
            artist_value = artist_form.cleaned_data['artist']
            song_value = song_form.cleaned_data['song']
            database_information = database_check()
            # Runs database_check function to return lists of artists and songs in the database

            if artist_value.upper() in database_information['artists'] and song_value.upper() in database_information['songs']:
                """Checks if the user input already existis in the database.
                If the user input exists in the database, view returns song inofrmation stored in the database, avoiding scraping the web """

                song_filter = Song.objects.filter(artist__artist__iexact=artist_value).filter(song__iexact=song_value)
                # Filters for searched artist and song, using iexact so the filter fields are case insensitive
                Song.objects.filter(artist__artist__iexact=artist_value).filter(song__iexact=song_value).update(searches=F('searches')+1)
                # If the song exists in the database, the searches field is increased by 1 using F. Default value is 1 for the first time a song is searched.
                return render(request, 'songs_app/lyrics.html', {'artist': song_filter[0].artist, 'song': song_filter[0].song, 'lyrics': song_filter[0].lyrics})

            else:
                web_lyrics = Lyrics(artist_value, song_value)
                # If the user input does not exist in the database, Lyrics instance is created
                try:
                    web_lyrics.fetch_data()
                    # fetch_data function is called to scrape the web
                except:
                    return render(request, 'songs_app/invalid_choice.html')
                    # Renders error page if user input is not valid
                else:
                    song = song_form.save(commit=False)
                    # Saves form input but doesnt commit to database
                    artist, created = Artist.objects.get_or_create(artist = web_lyrics.artist_name)
                    # Uses get_or_create to add artist to database if it doesnt exist already
                    song.lyrics = web_lyrics.song_lyrics
                    song.artist = artist
                    song.song = web_lyrics.song_name
                    case_artist = web_lyrics.artist_name
                    song.save()
                    # Stores artist, song and lyrics in corresponding fields in database
        return render(request, 'songs_app/lyrics.html', {'lyrics': song.lyrics, 'artist': case_artist, 'song': song.song})

    return render(request, 'songs_app/index.html', {'artist_form': artist_form, 'song_form': song_form})


def random_song(request):
    # View displays random song using random_song_generator function in queries.py
    if Song.objects.all():
        random_song = random_song_generator()
        return render(request, 'songs_app/random_song.html', {'artist': random_song['artist'], 'song': random_song['song'], 'lyrics': random_song['lyrics']} )
    else:
        return render(request, 'songs_app/invalid_choice.html', {'no_searches': True})

def top_songs(request):
    number_of_songs = len(Song.objects.all())
    if number_of_songs == 0:
        return render(request, 'songs_app/invalid_choice.html', {'no_searches': True})
    elif number_of_songs > 0 and number_of_songs < 10:
        top_songs = top_songs_generator()
        return render(request, 'songs_app/top_songs.html', {'artist_lst': top_songs['artist_lst'], 'song_lst' : top_songs['song_lst'], 'searches_lst': top_songs['searches_lst'], 'range' : range(number_of_songs)})
    else:
    # Renders top 10 songs to html page
        top_ten_songs = top_songs_generator()
        return render(request, 'songs_app/top_songs.html', {'artist_lst': top_ten_songs['artist_lst'], 'song_lst' : top_ten_songs['song_lst'], 'searches_lst': top_ten_songs['searches_lst'], 'range' : range(10)})


def lyrics(request):
    # Blank lyrics function needed to ensure lyrics.html page is rendered
    pass

songs_app/templates/songs_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "songs_app/css/base_styles.css" %}"/>
    {% block head_block %}

    {% endblock %}
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="navbar-nav">
        <a id="logo" class="navbar-brand" href="{% url 'songs_app:index' %}">S.L</a>
        <a class="nav-item nav-link" href="{% url 'songs_app:top_songs' %}">Top Songs</a>
        <a class="nav-item nav-link" href="{% url 'songs_app:random_song' %}">Random</a>
      </div>
    </nav>

    {% block body_block %}

    {% endblock %}

    </div>
  </body>
</html>

songs_app/templates/songs_app/index.html
{% extends "songs_app/base.html" %}
{% load static %}

{% block head_block %}
  <link rel="stylesheet" href="{% static "songs_app/css/index_style.css" %}"/>
{% endblock %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <div class="introduction">
        <h2>Welcome to Lyrics Generator</h2>
        <h3>Fill in details below to generate song lyrics</h3>
      </div>
        <div class="form">

          <form method="post" autocomplete="off">
              {{ artist_form.as_p }}
              {{ song_form.as_p }}
              {% csrf_token %}
              <input type="submit" class = "btn btn-primary" value="Submit">
          </form>
        </div>
    </div>
  </div>

{% endblock %}

songs_app/templates/songs_app/invalid_choice.html
{% extends "songs_app/base.html" %}
{% load static %}

{% block head_block %}
  <link rel="stylesheet" href="{% static "songs_app/css/invalid_choice_styles.css" %}"/>
{% endblock %}

{% block body_block %}
  <div class="container">
    <div class="jumbotron">
      <div class="invalid_choice">
        <h1>Invalid Choice, Try Again</h1>
        {% if no_searches %}
          <h2>No songs searched, search for a song and try again</h2>
        {% endif %}
        <a id='try_again' class="btn btn-primary" href="{% url 'songs_app:index' %}" role="button">Back</a>

      </div>
    </div>
  </div>

{% endblock %}

songs_app/templates/songs_app/lyrics.html
{% extends "songs_app/base.html" %}
{% load static %}

{% block head_block %}
  <link rel="stylesheet" href="{% static "songs_app/css/lyrics_styles.css" %}"/>
{% endblock %}

{% block body_block %}

    <div class="lyrics_background">
      <div class="container">
        <div class="lyrics">
          <h1>{{ artist }} Lyrics</h1>
          <br>
          <h3>"{{ song }}"</h3>
          {{ lyrics|linebreaks }}
        </div>
      </div>
    </div>

  {% endblock %}

songs_app/templates/songs_app/random_song.html
{% extends "songs_app/lyrics.html" %}

songs_app/templates/songs_app/top_songs.html
{% extends "songs_app/base.html" %}
{% load static %}
{% load my_extras %}

{% block head_block %}
  <link rel="stylesheet" href="{% static "songs_app/css/top_song_styles.css" %}"/>
{% endblock %}

{% block body_block %}

  <div class="container">
    <div class="jumbotron">

      <h1>Top 10 Songs:</h1>

      <table align = 'center'>
        <th>Position</th>
        <th>Artist</th>
        <th>Song</th>
        <th>Searches</th>
        {% for i in range %}
          <tr>
            <td> {{ i|add:1 }}</td>
            <td>{{ artist_lst|index:i }}</td>
            <td>{{ song_lst|index:i }}</td>
            <td>{{ searches_lst|index:i}}</td>
          </tr>
        {% endfor %}

      </table>
    </div>
  </div>

{% endblock %}